### PR TITLE
Responsive design

### PR DESCRIPTION
**Pull request by jessicafarias**
In this project, we build a responsive Website, using the media query.
#HEADER
-In the header, we have to create a responsive navbar

#MAIN
-In the main section, we create different sections that are responsive

#FOOTER
-In the footer section, we create

### CODE REVIEW

**Review by christianotieno — CHANGES_REQUESTED** [review]
# **CHANGES REQUIRED** :warning:
Hey @yahir91 & @jessicafarias  :wave:
-
You have done a splendid job! :tada: I love how clean and modular your code is. Keep it up.
We, however, do have some few changes to carry out before we proceed (see review comment).
##
## REQUIRED
### Medium Screen Changes
- [x] There seem to be some unnecessary spaces(margins) between the two articles section and the screen view borders. See the difference below 👇 

|[Source](https://thenextweb.com/)|[Clone](https://raw.githack.com/yahir91/TheNextWeb/version1/index.html)|
|:---:|:---:|
|two-articles|two-articles-clone|

- [x] The latest news section should be having four contents in one row. Please see the difference below 👇   

|[Source](https://thenextweb.com/)|[Clone](https://raw.githack.com/yahir91/TheNextWeb/version1/index.html)|
|:---:|:---:|
|latest-deals-medium|latest-deals-medium-clone|

- [x] The latest deals section should be having three contents in one row. Please see the difference below 👇 

|[Source](https://thenextweb.com/)|[Clone](https://raw.githack.com/yahir91/TheNextWeb/version1/index.html)|
|:---:|:---:|
|latest-deals|latest-deals-clone|

## OPTIONAL
- [x] We can as well use this [tool](https://jigsaw.w3.org/css-validator/validator) to validate our `media-query.css` file as well.
##
- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Comment by jessicafarias** [comment]
Thanks a lot for the review, it was really helpful.
- We already have fixed and updated the media-query file.
- We deleted all unnecessary spaces.

**Comment by jessicafarias** [comment]
Thanks a lot for the review, it was really helpful.

We already have fixed and updated the media-query file.
We deleted all unnecessary spaces.

**Comment by jessicafarias** [comment]
Thanks a lot for the review, it was really helpful.

We already have fixed and updated the media-query file.
We deleted all unnecessary spaces.

**Review by trekab — APPROVED** [review]
# Approved! :tada: 
Congratulations @jessicafarias and @yahir91, you have done an impressive job! :clap: 
You may now merge to master, submit the project completion form and continue to your next project.
_Happy coding!_ :wink: 
__Treasure Kabareebe__

**Pull request merged**
